export const SET_PERSONS = 'SET_PERSONS'
export const SET_LOADING_PERSON = 'SET_LOADING_PERSON'
export const SET_PERSON_ERROR = 'SET_PERSON_ERROR'

export const SET_PLANETS = 'SET_PLANETS'
export const SET_LOADING_PLANET = 'SET_LOADING_PLANET'
export const SET_PLANET_ERROR = 'SET_PLANET_ERROR'
