export const SET_PERSONS = 'SET_PERSONS'
export const SET_LOADING_PERSON = 'SET_LOADING_PERSON'
export const SET_PERSON_ERROR = 'SET_PERSON_ERROR'

export const SET_PLANETS = 'SET_PLANETS'
export const SET_LOADING_PLANET = 'SET_LOADING_PLANET'
export const SET_PLANET_ERROR = 'SET_PLANET_ERROR'

export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION'
export const SET_STEPS = 'SET_STEPS'
export const SET_TIMER = 'SET_TIMER'
export const SET_RUNNING = 'SET_RUNNING'
